version: 2
updates:
- package-ecosystem: nuget
  directory: "/src/BikeshareClient"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  reviewers:
  - andmos

- package-ecosystem: "docker"
  directory: "/"
  schedule:
    interval: "weekly"
  reviewers:
  - andmos 
  
- package-ecosystem: "github-actions"
  # Workflow files stored in the
  # default location of `.github/workflows`
  directory: "/"
  schedule:
    interval: "daily"
  reviewers:
  - andmos 
